#!/bin/bash

sauce=$(cat Gen?I* | grep 'Fitness');

IFS=$'\n'
for line in $sauce; do
	line=${line#*'Fitness:'};
	line=${line%%' <'*};
	echo "$line"
done
sauce=$(cat Gen1?I* | grep 'Fitness');
for line in $sauce; do
	line=${line#*'Fitness:'};
	line=${line%%' <'*};
	echo "$line"
done
sauce=$(cat Gen2?I* | grep 'Fitness');
for line in $sauce; do
	line=${line#*'Fitness:'};
	line=${line%%' <'*};
	echo "$line"
done
unset IFS
